[mgr]
prepend_keymap = [
    { on = [ "q" ], run = "plugin autosession -- save-and-quit", desc = "Save session and quit" },
    { on = [ "M" ], run = "plugin mount"},
    { on = [ "l" ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
    { on = [ "g", "i" ], run = "plugin lazygit", desc = "run lazygit"},
    { on = [ "R", "b" ], run = "plugin recycle-bin", desc = "Open recycle bin menu"},
    { on = [ ";" ], run = "plugin bunny", desc = "Start yazi.bunny"},
    { on = [ "'" ], run = "plugin bunny fuzzy", desc = "Start yazi.bunny fuzzy search"},
]
