[mgr]
prepend_keymap = [
    { on = [ "q" ], run = "plugin autosession -- save-and-quit", desc = "Save session and quit" },
    { on = [ "M" ], run = "plugin mount"},
    { on = [ "l" ], run = "plugin smart-enter", desc = "Enter the child directory, or open the file"},
    { on = [ "g", "i" ], run = "plugin lazygit", desc = "run lazygit"},
]
